### ISSUE TITLE
FEWD_Week1Assignment_Cookie-recipe

### ISSUE THREAD

**Issue by menaka1510** [menaka1510/FEWD_Week1#2]
Hi @wmyers I'm trying having trouble getting the CSS applied to a particular class (.spacebefore) on my CSS/HTML. 

The styles applied on the other classes seem to work, but not for this one....could you have a look and tell me where I'm going wrong? This is still a WIP - I'll work on this more tomorrow.

**Comment by wmyers** [comment]
Hi Menaka

Your cookie page is coming along great!

So there are two issues with your HTML markup for the `<hr>` tag:
- The `<hr>` tag is _empty_ so it does not require a closing tag
- The `<hr>` tag represents a break between paragraphs, whereas you have put two `<hr>`s _inside_ a `<p>` tag. (see [this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hr) for more info)

So just move your `<hr>`s so that they are outside of the `<p>`, coming before and after it.

Also don't forget to include an `@font-face` declaration at the top of your css file to be able to see the Museo font.

```
@font-face { font-family: Museo; src: url('fonts/Museo700-Regular.otf'); }
```

**Comment by menaka1510** [comment]
Hi @wmyers , Thanks for the feedback. I have now fixed the issues I was facing earlier and added in the @fontface tag as well..This is my final version of code for submission! Quite pleased with the result :) I'll update you once I have the other assignment complete..thanks again!

**Comment by wmyers** [comment]
Hi Menaka

Yes the cookie_recipe is looking very nice - well done! 

Be careful with overuse of negative margins for positioning. We'll talk about resetting CSS this week which you will find relevant.

How's the assignment pages coming along?

**Comment by menaka1510** [comment]
@wmyers , thanks for the feedback..will wait to learn about alignment properly and then update this code later.
